# Generated by Django 5.2 on 2026-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('services', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contraceptivemethod',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contraceptivemethod',
            name='suitability',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
