# Generated by Django 6.0.4 on 2026-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='profile_age_band',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='profile_goal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='profile_hormone_preference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='profile_relationship_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
