# Generated by Django 5.2 on 2026-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraceptivemethod',
            name='effectiveness',
            field=models.CharField(max_length=100),
        ),
    ]
