# Generated by Django 5.2 on 2026-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_contraceptivemethod_effectiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraceptivemethod',
            name='advantages',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contraceptivemethod',
            name='disadvantages',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contraceptivemethod',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contraceptivemethod',
            name='side_effects',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
