# Generated by Django 5.2 on 2026-03-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_contraceptivemethod_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='facility_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('health_center', 'Health Center'), ('private', 'Private Clinic')], default='health_center', max_length=20),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='offers_free_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
